name: Build and Test
on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # Note: all combinations of the following will be run independently
        os: [macos-latest, ubuntu-latest]
        swift: ["6.1.1"]
        config: [release]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift ${{ matrix.swift }} on ${{ matrix.os }}
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      # We disabled the separate build step, as it consumes extra CI time - building for testing apparently doesn't 
      # reuse the build cache from here, doubling the CI time.

      # - name: Build for ${{ matrix.swift }} on ${{ matrix.os }} with ${{ matrix.config }} configuration
      #   run: swift build -c ${{ matrix.config }}

      - name: Build & Test for ${{ matrix.swift }} on ${{ matrix.os }} with ${{ matrix.config }} configuration
        run: swift test -c ${{ matrix.config }}

    runs-on: ${{ matrix.os }}
