name: Build and Test
on: push

jobs:
  test:
    strategy:
      matrix:
        # Note: all combinations of the following will be run independently
        os: [ macos-latest, ubuntu-latest ]
        swift: [ '6.1' ]
        config: [ debug, release ]

        # Fail fast can be set to false to allow all jobs in matrix to complete
        # even if one fails. Default is true.
        # fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift ${{ matrix.swift }} on ${{ matrix.os }}
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - name: Build for ${{ matrix.swift }} on ${{ matrix.os }} with ${{ matrix.config }} configuration
        run: swift build -c ${{ matrix.config }}

      - name: Test for ${{ matrix.swift }} on ${{ matrix.os }} with ${{ matrix.config }} configuration
        run: swift test -c ${{ matrix.config }}

    runs-on: ${{ matrix.os }}